### ISSUE TITLE
Can't open my old key

### ISSUE THREAD

**Issue by xaozai** [Revertron/Alfis#105]
When I try to open my old key, it doesn't open, I get this:
```
18:19:16 [WARN] alfis::keystore: Loaded key from OLD format! Please, resave it!
18:19:16 [INFO] alfis::web_ui: Loaded keystore with keys: 72931D5EC6253820BE4EE8DC1745CF51B3ABB70917F57ACAE928DDF4F0C9ED3F, 09F53DECA7CDE8661F603072B4C1231FD63F4D80D6DFD31DDEA5631888F2A492
thread 'webui' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: Some(1), message: Some("no such column: signing") }', src/blockchain/chain.rs:601:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'webui' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/web_ui.rs:200:44
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/p2p/network.rs:152:58
```

**Comment by xaozai** [comment]
The error occurs when the old database exists.

**Comment by Revertron** [comment]
Of course! :)
